#!/bin/bash
set -e

copy_dep() {
  name=$1
  echo "copy dep for $name"
  ldd $name | grep -v linux-vdso | grep -v ld-linux | awk -F\> '{print $2}' | sed 's/(.\+)//' | while \
    read line; do
     if test -f $line; then
       cp $line $DEST
     fi
  done
}
# This script exists as backwards compatibility for CI
(
    DEST="${DEST}-client"
    ABS_DEST="${ABS_DEST}-client"
    . hack/make/dynbinary-client
    BINARY_SHORT_NAME='docker'
    BINARY_NAME="$BINARY_SHORT_NAME-$VERSION"
    BINARY_EXTENSION="$(binary_extension)"
    BINARY_FULLNAME="$BINARY_NAME$BINARY_EXTENSION"
    copy_dep $DEST/$BINARY_FULLNAME
)
(

    DEST="${DEST}-daemon"
    ABS_DEST="${ABS_DEST}-daemon"
    . hack/make/dynbinary-daemon
    BINARY_SHORT_NAME='dockerd'
    BINARY_NAME="$BINARY_SHORT_NAME-$VERSION"
    BINARY_EXTENSION="$(binary_extension)"
    BINARY_FULLNAME="$BINARY_NAME$BINARY_EXTENSION"
    copy_dep $DEST/$BINARY_FULLNAME
    cp /usr/local/bin/docker-* $DEST/
)

